# wrangler.toml
name = "gemini-pr"
main = "worker/src/index.ts"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "public"

[observability]
enabled = true

[[kv_namespaces]]
binding = "GEMINI_KEYS_KV"
id = "58e9d9179c134ef6a8cfc8143f52ec38"

[[kv_namespaces]]
binding = "WORKER_CONFIG_KV"
id = "58e9d9179c134ef6a8cfc8143f52ec38"
